### ISSUE TITLE
EKF: Problem with quaternion covariance reset

### ISSUE THREAD

**Issue by priseborough** [PX4/ecl#541] opened 2018-12-20 22:06 UTC
When doing a yaw reset using the Ekf::initialiseQuatCovariances(Vector3f &rot_vec_var) method  (see https://github.com/PX4/ecl/blob/master/EKF/ekf_helper.cpp#L1429) if the vehicle has a large roll or pitch angle (eg tailsitter), the use of a rotation vector variance to represent the uncertainty does not enable the uncertainty in yaw to be changed without affecting the tilt (roll/pitch) variance.

A better method is required.

**Comment by priseborough** [comment] 2018-12-20 23:44
I've derived equations that should enable the yaw uncertainty to be increased. This will eliminate the need for a all of nothing reset of quaternion covariances following a reset of the yaw angle.

See  https://github.com/PX4/ecl/tree/pr-ekfYawCovReset

This will be implemented in the new year.

**Comment by priseborough** [comment] 2018-12-23 22:49
Further investigation of the code showed that this part of a wider issue that can affect all vehicle types that need to use an in-air reset to recover from a ground based magnetic yaw error. This is due to:

1) The preservation of off-diagonal elements in the covariance matrix in the 0-3 (quaternion state index) rows and columns that can lead to incorrect fusion of GPS and other NE frame observations following a state reset
2) The failure to preserve exisiting correlation information in the [4x4] quaternion state covariance sub-matrix when a full reset is applied.

Fundamentally the exisiting approach to handling the reset of covariances after a yaw reset was 'all or nothing'. 

The investigation also revealed that the reset of the yaw angle to enable recovery from ground based magnetic anomally is conditional on switching to 3-axis fusion and can therefore fail to execute depending on the setting of EKF2_MAG_TYPE and the flight profile. Changes to fix this hae been pushed to https://github.com/PX4/ecl/tree/pr-ekfYawCovReset. 

A PR will be submitted follong further testing. To assist with this a modification to the sitl_gazebo simulaton is being used that includes a crude model of a ground based magnetic anomally - see https://github.com/priseborough/sitl_gazebo/tree/earthFrameMagError

**Comment by priseborough** [comment] 2018-12-24 00:06
I was able to simulate a large tilt angle at the time fo the yaw reset by using the 'make posix_sitl gazebo_tailsitter' option, however this did require disabling the "Preflight Fail: Airspeed Sensor stuck" chekc in the commander and changing the  step size and real time update rate in tailsitter.world to 250 Hz, eg     <max_step_size>0.004</max_step_size>
<real_time_update_rate>250</real_time_update_rate>

Result with only critical yaw reset bug fix applied: https://logs.px4.io/plot_app?log=7e5f40a7-00d7-49c7-a0a6-8d422144a907

Innovations:
![screen shot 2018-12-24 at 11 00 50 am](https://user-images.githubusercontent.com/3596952/50388461-32ff5480-076b-11e9-8955-0bb8e0df0096.png)

Quaternion Variances:
![screen shot 2018-12-24 at 11 01 32 am](https://user-images.githubusercontent.com/3596952/50388464-59bd8b00-076b-11e9-8969-0f7aee5b8df9.png)

Test with all https://github.com/PX4/ecl/tree/pr-ekfYawCovReset changes: https://logs.px4.io/plot_app?log=69dd8220-570d-4897-be79-e2290eedcbd7

Innovations:
![screen shot 2018-12-24 at 11 05 09 am](https://user-images.githubusercontent.com/3596952/50388474-d8b2c380-076b-11e9-9946-6cebd8c0de54.png)

Quaternion Variances:
![screen shot 2018-12-24 at 11 05 55 am](https://user-images.githubusercontent.com/3596952/50388478-e8320c80-076b-11e9-8295-c2e3b05281b6.png)

**Comment by CarlOlsson** [comment] 2019-01-04 15:36
@priseborough 
I tested this for a quad in sitl
![image](https://user-images.githubusercontent.com/7795133/50695251-7a73c380-103c-11e9-8937-7d10a0a6ebc1.png)

As can be seen the variance for the q[0] and q[3] is increased which is correct.

> I was able to simulate a large tilt angle at the time of the yaw reset by using the 'make posix_sitl gazebo_tailsitter' option

Are you sure about this? As far as I know standard PX4 uses a convention for tailsitters such that the coordinate frame is similar to that of a quad in hover. I.e. in cruise the tailsitter flies along -z direction.

Without doing a hand held test with a real system I am not sure how to test the reset at high pitch angles in SITL. However, I pulled in the changes to our code base and this is result

![image](https://user-images.githubusercontent.com/7795133/50696005-98dabe80-103e-11e9-98e7-f5ef39c8a7ff.png)

This seems incorrect since the variance of all quaternion states increased with a similar amount

**Comment by CarlOlsson** [comment] 2019-01-07 14:03
@priseborough 
I tested this code by adding the entire 4x4 quaternion covariance matrix to logging and running
```
make px4_sitl gazebo
```
[Link to logfile](https://logs.px4.io/plot_app?log=4021dadc-e1aa-4c60-abc9-f07074037787)

I then converted the quaternion covariance matrix to an Euler covariance matrix following [these equations](https://stats.stackexchange.com/questions/119780/what-does-the-covariance-of-a-quaternion-mean)
(They are the same as the ones used [here](https://github.com/PX4/ecl/pull/543/files#diff-6ff089a846fa4bd452bf076e28a0bef7R994))

However, the result is not as expected, the blue and green lines overlap so the largest increase in variance is in the middle diagonal element (pitch).
![image](https://user-images.githubusercontent.com/7795133/50772132-0a0fb100-128d-11e9-8817-e27f5b828955.png)

**Comment by priseborough** [comment] 2019-01-08 08:06
However if you plot the quaternion state variances, the biggest increase is in q3 and less for q0 with q1  and q2 variance increase being negligible  which is consistent with an increase in yaw uncertainty for a vehicle that is close to zero roll and pitch.

**Comment by CarlOlsson** [comment] 2019-01-08 08:16
Yes, which indicates that the code is working as intended. I just need to figure out why the conversion to Euler angles does not give the expected result

**Comment by TSC21** [comment] 2019-01-08 08:37
@CarlOlsson I think it's related with the 321 and 312 variations that Paul spoke of and I think I know how to handle those on the covariance law. I will do an update later today.

**Comment by CarlOlsson** [comment] 2019-01-08 09:15
Yes me to, I just did a test with a quad. Hover for some time, increase heading noise, hover, decrease heading noise
![image](https://user-images.githubusercontent.com/7795133/50820927-362f3e80-132e-11e9-9b64-2ad1cb7f031e.png)

The middle element in the covariance matrix is definitely yaw and not pitch

**Comment by CarlOlsson** [comment] 2019-01-09 16:50
Okey, so the confusion around the quaternion convention is sorted out in https://github.com/PX4/ecl/pull/543

What is left for this PR is to verify that the yaw uncertainty is increasing correctly for all attitudes, e.g. at pitch 90 degrees. 
In order to do that I calculated the Jacobian of the Euler angles to quaternions for both a 321 and 312 sequence.
Comparing the yaw variance on the logfile described [here](https://github.com/PX4/ecl/pull/543#issuecomment-452350609) gives the following result

![image](https://user-images.githubusercontent.com/7795133/50913973-df149100-1435-11e9-957d-e96016a759fb.png)

This seems correct.

I then simulated a flight where the vehicle flew in a square (standard attitude, so body z facing down). In the middle of every leg I triggered `uncorrelateQuatStates()` and ```increaseQuatYawErrVariance()```

This is the result
![image](https://user-images.githubusercontent.com/7795133/50914446-d7a1b780-1436-11e9-83dc-ae1683b8f43a.png)

As can be seen the variance from the 321 sequence seems correct. but for the 312 sequence something is strange, for the east and west direction no increase of uncertainty is observed

**Comment by CarlOlsson** [comment] 2019-01-09 16:57
For reference, here is the G matrices 

```
    #  Yaw using 321 Euler sequence
    G321[0][0] = 2*q4*(-2*q3**2 - 2*q4**2 + 1)/((2*q1*q4 + 2*q2*q3)**2 + (-2*q3**2 - 2*q4**2 + 1)**2)
    G321[0][1] = 2*q3*(-2*q3**2 - 2*q4**2 + 1)/((2*q1*q4 + 2*q2*q3)**2 + (-2*q3**2 - 2*q4**2 + 1)**2)
    G321[0][2] = 2*q2*(-2*q3**2 - 2*q4**2 + 1)/((2*q1*q4 + 2*q2*q3)**2 + (-2*q3**2 - 2*q4**2 + 1)**2) - 4*q3*(-2*q1*q4 - 2*q2*q3)/((2*q1*q4 + 2*q2*q3)**2 + (-2*q3**2 - 2*q4**2 + 1)**2)
    G321[0][3] = 2*q1*(-2*q3**2 - 2*q4**2 + 1)/((2*q1*q4 + 2*q2*q3)**2 + (-2*q3**2 - 2*q4**2 + 1)**2) - 4*q4*(-2*q1*q4 - 2*q2*q3)/((2*q1*q4 + 2*q2*q3)**2 + (-2*q3**2 - 2*q4**2 + 1)**2)
    
    # Yaw using 312 Euler sequence
    G312[0][0] = 2*q1*(-2.0*q1*q4 + 2.0*q2*q3)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2) + 2.0*q4*(q1**2 - q2**2 + q3**2 - q4**2)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2)
    G312[0][1] = -2*q2*(-2.0*q1*q4 + 2.0*q2*q3)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2) - 2.0*q3*(q1**2 - q2**2 + q3**2 - q4**2)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2)
    G312[0][2] = -2.0*q2*(q1**2 - q2**2 + q3**2 - q4**2)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2) + 2*q3*(-2.0*q1*q4 + 2.0*q2*q3)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2)
    G312[0][3] = 2.0*q1*(q1**2 - q2**2 + q3**2 - q4**2)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2) - 2*q4*(-2.0*q1*q4 + 2.0*q2*q3)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2)
```

**Comment by TSC21** [comment] 2019-01-09 17:03
@CarlOlsson have you tried to use the same G matrix for both 321 and 312 rotation orders? I tried to use the same for these and I seemed to get the same results on plots.

**Comment by CarlOlsson** [comment] 2019-01-09 17:07
> @CarlOlsson have you tried to use the same G matrix for both 321 and 312 rotation orders? I tried to use the same for these and I seemed to get the same results on plots.

I don't understand what you mean. The Jacobian (G matrix) is defined by the way you calculate the yaw angle which depends on the Euler sequence. How can you have different Euler sequences with the same Jacobian?

**Comment by TSC21** [comment] 2019-01-09 17:09
I can't really tell but for the 321 and 123 orders, applying the same G matrix, I get the same results. I can try to verify that on math.

**Comment by CarlOlsson** [comment] 2019-01-09 17:11
> We probably need to face that case as well, though I am not sure how we identify the rotation order on the function so to apply the proper G matrix.

You can probably use the same method as [here](https://github.com/PX4/ecl/blob/master/EKF/mag_fusion.cpp#L441)

For the logfile mentioned above, here is the raw quaternions
**East**
![image](https://user-images.githubusercontent.com/7795133/50915825-e76ecb00-1439-11e9-8d77-9bcdd2a7eddc.png)

**North**
![image](https://user-images.githubusercontent.com/7795133/50915830-ea69bb80-1439-11e9-93b5-2958c7f7d34e.png)

**West**
![image](https://user-images.githubusercontent.com/7795133/50915842-edfd4280-1439-11e9-9c56-55c8110c6255.png)

**South**
![image](https://user-images.githubusercontent.com/7795133/50915854-f2296000-1439-11e9-876b-d643b5f4b018.png)

**Comment by CarlOlsson** [comment] 2019-01-10 16:14
I tested this code again, this time on a sitl quad.
I planned a square mission ([log](https://logs.px4.io/plot_app?log=1ed88263-d4ef-4901-80e5-9148a4e376f8)), all waypoints are 45 second loiter
![image](https://user-images.githubusercontent.com/7795133/50978677-33cb1100-14f5-11e9-9fb9-f8eeb9aaad42.png)

Then at every waypoint I triggered uncorrelateQuatStates() and increaseQuatYawErrVariance() two times

This time I sometimes got 
```EKF mag yaw fusion numerical error - covariance reset```
when I triggered it.

Comparing the yaw variance calculated using the 321 and 312 Euler sequence looks like this
![image](https://user-images.githubusercontent.com/7795133/50981226-cae69780-14fa-11e9-96e6-c4496bb7cb7e.png)

As can be seen they give similar result for the north/south direction but not for east/west. I don't know why at the moment.

yaw for the 312 calculation is given by
```yaw = atan2(-2.0 * (q2 * q3 - q1 * q4), q1 * q1 - q2 * q2 + q3 * q3 - q4 * q4)```

and the G matrix is:
```
G[0][0] = 2*q1*(-2.0*q1*q4 + 2.0*q2*q3)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2) + 2.0*q4*(q1**2 - q2**2 + q3**2 - q4**2)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2)
G[0][1] = -2*q2*(-2.0*q1*q4 + 2.0*q2*q3)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2) - 2.0*q3*(q1**2 - q2**2 + q3**2 - q4**2)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2)
G[0][2] = -2.0*q2*(q1**2 - q2**2 + q3**2 - q4**2)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2) + 2*q3*(-2.0*q1*q4 + 2.0*q2*q3)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2)
G[0][3] = 2.0*q1*(q1**2 - q2**2 + q3**2 - q4**2)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2) - 2*q4*(-2.0*q1*q4 + 2.0*q2*q3)/((2.0*q1*q4 - 2.0*q2*q3)**2 + (q1**2 - q2**2 + q3**2 - q4**2)**2)
```

**Comment by priseborough** [comment] 2019-01-11 08:59
Where are you getting the derivation for the conversion from  a quaternion rotation to a 312 Tait-Bryan sequence and the derivation for the associated partial derivative matrix?

**Comment by CarlOlsson** [comment] 2019-01-11 09:06
The conversion from quaternion rotation to a rotation matrix comes from [here](https://github.com/PX4/ecl/blob/master/EKF/ekf_helper.cpp#L1354), and then to 312 Tait-Bryan yaw comes from [here](https://github.com/PX4/ecl/blob/master/EKF/mag_fusion.cpp#L546)

The derivation for the partial derivative matrix comes from the following python script
```
from sympy import *
q1, q2, q3, q4 = symbols('q1 q2 q3 q4')

yaw = atan2(-2.0 * (q2 * q3 - q1 * q4), q1 * q1 - q2 * q2 + q3 * q3 - q4 * q4)
yaw_q1 = diff(yaw, q1)
yaw_q2 = diff(yaw, q2)
yaw_q3 = diff(yaw, q3)
yaw_q4 = diff(yaw, q4)

print('G[0][0] = ' + str(yaw_q1))
print('G[0][1] = ' + str(yaw_q2))
print('G[0][2] = ' + str(yaw_q3))
print('G[0][3] = ' + str(yaw_q4))
```

**Comment by priseborough** [comment] 2019-01-14 01:03
I've done further investigation today and the "EKF mag yaw fusion numerical error - covariance reset" could be the result of setting the off-diagonals to zero and having fusion take place before the next covariance prediction. How were you triggering uncorrelateQuatStates() and increaseQuatYawErrVariance() ? I will add code to the branch so that the fusion is blocked until after the next covariance prediction.

Using Matlab I independently derived the Tait-Bryan first rotation (yaw) in a 312 sequence as a function of the quaternions and got

yaw = atan2(2*q0*q3 - 2*q1*q2, q0^2 - q1^2 + q2^2 - q3^2);

d_yaw/d_q0 =

(((2*q3)/(q0^2 - q1^2 + q2^2 - q3^2) - (2*q0*(2*q0*q3 - 2*q1*q2))/(q0^2 - q1^2 + q2^2 - q3^2)^2)*(q0^2 - q1^2 + q2^2 - q3^2)^2)/((2*q0*q3 - 2*q1*q2)^2 + (q0^2 - q1^2 + q2^2 - q3^2)^2);

d_yaw/d_q1 =

-(((2*q2)/(q0^2 - q1^2 + q2^2 - q3^2) - (2*q1*(2*q0*q3 - 2*q1*q2))/(q0^2 - q1^2 + q2^2 - q3^2)^2)*(q0^2 - q1^2 + q2^2 - q3^2)^2)/((2*q0*q3 - 2*q1*q2)^2 + (q0^2 - q1^2 + q2^2 - q3^2)^2);

d_yaw/d_q2 =

-(((2*q1)/(q0^2 - q1^2 + q2^2 - q3^2) + (2*q2*(2*q0*q3 - 2*q1*q2))/(q0^2 - q1^2 + q2^2 - q3^2)^2)*(q0^2 - q1^2 + q2^2 - q3^2)^2)/((2*q0*q3 - 2*q1*q2)^2 + (q0^2 - q1^2 + q2^2 - q3^2)^2);

d_yaw/d_q3 =

(((2*q0)/(q0^2 - q1^2 + q2^2 - q3^2) + (2*q3*(2*q0*q3 - 2*q1*q2))/(q0^2 - q1^2 + q2^2 - q3^2)^2)*(q0^2 - q1^2 + q2^2 - q3^2)^2)/((2*q0*q3 - 2*q1*q2)^2 + (q0^2 - q1^2 + q2^2 - q3^2)^2);

[TaitBryan312.m.txt](https://github.com/PX4/ecl/files/2753786/TaitBryan312.m.txt)

**Comment by priseborough** [comment] 2019-01-15 12:15
OK, so I will focus the investigation for the time being on the cause of the 'EKF mag yaw fusion numerical error - covariance reset' events. One thing to try is to ensure the covariance prediction runs before the next fusion step.

I would like to be able to reproduce your results in my testing using the same mission plan and firmware modifications.

**Comment by priseborough** [comment] 2019-01-16 06:55
Thank you to @CarlOlsson and Sebastian for spotting a sign error that was introduced when the auto-code had been cleaned up by hand in the increaseQuatYawErrVariance function. The https://github.com/PX4/ecl/tree/pr-ekfYawCovReset branch has been rebased has been rebased and the error fixed here: 
https://github.com/PX4/ecl/commit/69c29ad0e5e6db60ebc29ac537e87fa5301c29ff

A compile error introduced when the a rebase conflict was resolved has also been fixed - see 
https://github.com/PX4/ecl/commit/47cf16f8e3f727370aab0e2524f35d31d95ff1a3

**Comment by CarlOlsson** [comment] 2019-01-16 11:18
@priseborough As discussed I pushed two commits to this branch.
3d716c438d28e0d0c2c42205a8bdbddccab146d7 Also fill in the lower part of the covariance matrix
d36be5b3bd3707c805fc6773906f2ba4dce87498 Limit the yaw variance increase to 0.01 rad^2

**Comment by priseborough** [comment] 2019-01-17 04:05
@CarlOlsson I've pushed two commits to the branch which should address the issue of unstable declination immediately following a field reset when using 3-axis fusion and the loss of declination covariance information when switching in and out of 3-axis fusion in auto mode in into 3-axis fusion with EKf2_MAG_TYPE = 0

**Comment by CarlOlsson** [comment] 2019-01-18 16:13
Actually not only [this](https://github.com/PX4/ecl/issues/554) problem seems to be initializing the covariances to zero

There is also a problem when we call fuseDeclination() in resetMagYaw(). When we call this function the first time we activate 3d fusion we also call fixCovarianceErrors(), and here we set the mag field state covariances to zero since _control_status.flags.mag_3D is false

**Comment by priseborough** [comment] 2019-01-20 23:37
The covariance reset to 0 bug has been fixed here: 
https://github.com/PX4/ecl/commit/ad9414e4dadc6a7a25d33b7edc219775d8a88086

SITL log: https://logs.px4.io/plot_app?log=39f319e4-847f-467c-9056-78fb917c0515

**Comment by LorenzMeier** [comment] 2019-01-21 00:10
@priseborough I've put up a PR for easier reference to that commit: https://github.com/PX4/ecl/pull/556

**Comment by CarlOlsson** [comment] 2019-01-21 14:05
@priseborough Some comments to the updated code in this branch

1) The `fuseDeclination()` function in `resetMagHeading()` is never triggered [here](https://github.com/PX4/ecl/blob/ad9414e4dadc6a7a25d33b7edc219775d8a88086/EKF/ekf_helper.cpp#L705-L705) because `_control_status.flags.mag_3D` is always false.

2) This is actually also on master but since https://github.com/PX4/ecl/pull/544 the reset logic in controlMagFusion() is never triggered
https://github.com/PX4/ecl/blob/ad9414e4dadc6a7a25d33b7edc219775d8a88086/EKF/control.cpp#L1455-L1470
since `_control_status.flags.mag_align_complete` is always set to true [here](https://github.com/PX4/ecl/blob/ad9414e4dadc6a7a25d33b7edc219775d8a88086/EKF/control.cpp#L1391-L1391)

**Comment by priseborough** [comment] 2019-01-21 22:13
@CarlOlsson  I will try another approach to simplify the way fuseDeclination() is only called, either immediately before fuseMag() if it hasn't been called since the last yaw reset or immediately after if _control_status.flags.mag_dec is true. This will simplify the overall logic.

Discussion continued in PR.

**Comment by mhkabir** [comment] 2019-02-01 09:10
Fixed on master.

**Closed by mhkabir** 2019-02-01 09:10 UTC
Labels: bug, ekf
